runtime: python27
api_version: 1
threadsafe: true
instance_class: F2
automatic_scaling:
  min_idle_instances: 1

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"

handlers:
- url: /tasks(:?/.*)?
  script: main.tasks
  secure: always
  login: admin
  auth_fail_action: unauthorized

- url: /static
  static_dir: static

- url: /.*
  script: main.app
